apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
  labels:
    app: book-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
        - name: book-api
          image: book-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: mongodb://mongo:27017/bookshelf
            - name: JWT_SECRET
              value: change-me-in-production
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
